### PR TITLE
Add support for boolean soft-deletion

### PR DESCRIPTION
**Pull request by ben221199**
This PR adds support for boolean soft-deletion.

### CODE REVIEW

**Comment by lindyhopchris** [comment]
Sorry, I hadn't realised how extensive these changes would be.

Really this should have a separate driver, and a separate trait to the `SoftDeletes` trait this package already has. As it relies on a package that wouldn't normally be installed, I think maybe this needs to be `laravel-json-api/boolean-softdeletes`. Or you could publish as your own package? What's your preference?

**Comment by lindyhopchris** [comment]
Not sure how you're installing the boolean-softdeletes package, as it hasn't been updated for Laravel 8?

**Comment by ben221199** [comment]
I use https://github.com/ben221199/laravel-boolean-softdeletes, but I haven't made a PR yet.

**Comment by lindyhopchris** [comment]
Ok, that makes sense. Shall I set up `laravel-json-api/boolean-softdeletes` or did you want to own the package?

**Comment by ben221199** [comment]
Well, I was thinking about updating the orginal repository using a PR. You could always choose for yourself if you want your own boolean-softdeletes repository as long as it has the `getIsDeletedColumn`, but do you want it under the laravel-json-api organisation? It isn't really connected to that.

**Comment by ben221199** [comment]
I have made a pull request for the library: https://github.com/tenantcloud/laravel-boolean-softdeletes/pull/7

**Comment by ben221199** [comment]
The pull request is merged, so if you want to implement boolean soft-deletes, I would go for the official package: `tenantcloud/laravel-boolean-softdeletes`.

**Comment by lindyhopchris** [comment]
@ben221199 cheers, thanks for letting me know.

**Comment by lindyhopchris** [comment]
Closing this in favour of [laravel-json-api/boolean-softdeletes](https://github.com/laravel-json-api/boolean-softdeletes)

FYI that package will be ready to tag when the following PRs are merged:
https://github.com/tenantcloud/laravel-boolean-softdeletes/pull/9
https://github.com/tenantcloud/laravel-boolean-softdeletes/pull/8

Those PRs are required to ensure the JSON:API boolean soft deletes implementation matches the standard soft deletes implementation.

**Pull request closed without merging**
